//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MinjustService_getSubjectByName
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tunduk.gov.kg", ConfigurationName="MinjustService_getSubjectByName.SubjectByNamePort")]
    public interface SubjectByNamePort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(XRoadIdentifierType))]
        System.Threading.Tasks.Task<MinjustService_getSubjectByName.getSubjectByNameResponse1> getSubjectByNameAsync(MinjustService_getSubjectByName.getSubjectByNameRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadClientIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadLocalGroupIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadGlobalGroupIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadSecurityServerIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadCentralServiceIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadSecurityCategoryIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadServiceIdentifierType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(XRoadClientIdentifierType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadIdentifierType
    {
        
        private string xRoadInstanceField;
        
        private string memberClassField;
        
        private string memberCodeField;
        
        private string subsystemCodeField;
        
        private string groupCodeField;
        
        private string serviceCodeField;
        
        private string serviceVersionField;
        
        private string securityCategoryCodeField;
        
        private string serverCodeField;
        
        private XRoadObjectType objectTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string xRoadInstance
        {
            get
            {
                return this.xRoadInstanceField;
            }
            set
            {
                this.xRoadInstanceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string memberClass
        {
            get
            {
                return this.memberClassField;
            }
            set
            {
                this.memberClassField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string memberCode
        {
            get
            {
                return this.memberCodeField;
            }
            set
            {
                this.memberCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string subsystemCode
        {
            get
            {
                return this.subsystemCodeField;
            }
            set
            {
                this.subsystemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string groupCode
        {
            get
            {
                return this.groupCodeField;
            }
            set
            {
                this.groupCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string serviceCode
        {
            get
            {
                return this.serviceCodeField;
            }
            set
            {
                this.serviceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string serviceVersion
        {
            get
            {
                return this.serviceVersionField;
            }
            set
            {
                this.serviceVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string securityCategoryCode
        {
            get
            {
                return this.securityCategoryCodeField;
            }
            set
            {
                this.securityCategoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string serverCode
        {
            get
            {
                return this.serverCodeField;
            }
            set
            {
                this.serverCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified)]
        public XRoadObjectType objectType
        {
            get
            {
                return this.objectTypeField;
            }
            set
            {
                this.objectTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public enum XRoadObjectType
    {
        
        /// <remarks/>
        MEMBER,
        
        /// <remarks/>
        SUBSYSTEM,
        
        /// <remarks/>
        SERVER,
        
        /// <remarks/>
        GLOBALGROUP,
        
        /// <remarks/>
        LOCALGROUP,
        
        /// <remarks/>
        SECURITYCATEGORY,
        
        /// <remarks/>
        SERVICE,
        
        /// <remarks/>
        CENTRALSERVICE,
    }
    



    /// <MYCODE>
    
    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
    public partial class subjects
    {

        private string fullNameGlField;

        private string shortNameGlField;

        private string fullNameOlField;

        private string shortNameOlField;

        private bool foreignPartField;

        private string registrCodeField;

        private uint statSubCodeField;

        private string tinField;

        private string regionField;

        private string districtField;

        private string cityField;

        private string microdistrictField;

        private string streetField;

        private string houseField;

        private string roomField;

        private string phonesField;

        private object email1Field;

        private System.DateTime orderDateField;

        private byte ownershipField;

        private byte categoryField;

        private string chiefField;

        private string descriptionField;

        private string baseBusinessCodeField;

        private string baseBusCodeField;

        private ushort indFoundersField;

        private byte jurFoundersField;

        private ushort totalFoundersField;

        private founder[] founderField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string fullNameGl
        {
            get
            {
                return this.fullNameGlField;
            }
            set
            {
                this.fullNameGlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string shortNameGl
        {
            get
            {
                return this.shortNameGlField;
            }
            set
            {
                this.shortNameGlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string fullNameOl
        {
            get
            {
                return this.fullNameOlField;
            }
            set
            {
                this.fullNameOlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string shortNameOl
        {
            get
            {
                return this.shortNameOlField;
            }
            set
            {
                this.shortNameOlField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public bool foreignPart
        {
            get
            {
                return this.foreignPartField;
            }
            set
            {
                this.foreignPartField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string registrCode
        {
            get
            {
                return this.registrCodeField;
            }
            set
            {
                this.registrCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public uint statSubCode
        {
            get
            {
                return this.statSubCodeField;
            }
            set
            {
                this.statSubCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string tin
        {
            get
            {
                return this.tinField;
            }
            set
            {
                this.tinField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string district
        {
            get
            {
                return this.districtField;
            }
            set
            {
                this.districtField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string microdistrict
        {
            get
            {
                return this.microdistrictField;
            }
            set
            {
                this.microdistrictField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string street
        {
            get
            {
                return this.streetField;
            }
            set
            {
                this.streetField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string house
        {
            get
            {
                return this.houseField;
            }
            set
            {
                this.houseField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string room
        {
            get
            {
                return this.roomField;
            }
            set
            {
                this.roomField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string phones
        {
            get
            {
                return this.phonesField;
            }
            set
            {
                this.phonesField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public object email1
        {
            get
            {
                return this.email1Field;
            }
            set
            {
                this.email1Field = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg", DataType = "date")]
        public System.DateTime orderDate
        {
            get
            {
                return this.orderDateField;
            }
            set
            {
                this.orderDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public byte ownership
        {
            get
            {
                return this.ownershipField;
            }
            set
            {
                this.ownershipField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public byte category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string chief
        {
            get
            {
                return this.chiefField;
            }
            set
            {
                this.chiefField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string baseBusinessCode
        {
            get
            {
                return this.baseBusinessCodeField;
            }
            set
            {
                this.baseBusinessCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public string baseBusCode
        {
            get
            {
                return this.baseBusCodeField;
            }
            set
            {
                this.baseBusCodeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public ushort indFounders
        {
            get
            {
                return this.indFoundersField;
            }
            set
            {
                this.indFoundersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public byte jurFounders
        {
            get
            {
                return this.jurFoundersField;
            }
            set
            {
                this.jurFoundersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace = "http://tunduk.gov.kg")]
        public ushort totalFounders
        {
            get
            {
                return this.totalFoundersField;
            }
            set
            {
                this.totalFoundersField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("founder", Namespace = "http://tunduk.gov.kg")]
        public founder[] founder
        {
            get
            {
                return this.founderField;
            }
            set
            {
                this.founderField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tunduk.gov.kg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tunduk.gov.kg", IsNullable = false)]
    public partial class founder
    {

        private string fullNameField;

        private string citizenshipField;

        private string tinField;

        /// <remarks/>
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }

        /// <remarks/>
        public string citizenship
        {
            get
            {
                return this.citizenshipField;
            }
            set
            {
                this.citizenshipField = value;
            }
        }

        /// <remarks/>
        public string tin
        {
            get
            {
                return this.tinField;
            }
            set
            {
                this.tinField = value;
            }
        }
    }

    /// <remarks/>
    [System.SerializableAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://tunduk.gov.kg")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://tunduk.gov.kg", IsNullable = false)]
    public partial class getSubjectByNameResponse
    {

        private subjects[] subjectsField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("subjects", Namespace = "")]
        public subjects[] subjects
        {
            get
            {
                return this.subjectsField;
            }
            set
            {
                this.subjectsField = value;
            }
        }
    }
    
    /// </MYCODE>








    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://tunduk.gov.kg")]
    public enum QueryType
    {
        NAME,
        OKPO,
        HEAD,
        FOUNDER,
        DESCRIPTION
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tunduk.gov.kg")]
    public partial class getSubjectByNameRequest
    {
        
        private string queryField;
        
        private QueryType typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string query
        {
            get
            {
                return this.queryField;
            }
            set
            {
                this.queryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public QueryType type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
       
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadLocalGroupIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadGlobalGroupIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadSecurityServerIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadCentralServiceIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadSecurityCategoryIdentifierType : XRoadIdentifierType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://x-road.eu/xsd/identifiers")]
    public partial class XRoadServiceIdentifierType : XRoadIdentifierType
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSubjectByNameRequest1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public MinjustService_getSubjectByName.XRoadClientIdentifierType client;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public MinjustService_getSubjectByName.XRoadServiceIdentifierType service;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string userId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string id;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string protocolVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tunduk.gov.kg", Order=0)]
        public MinjustService_getSubjectByName.getSubjectByNameRequest getSubjectByNameRequest;
        
        public getSubjectByNameRequest1()
        {
        }
        
        public getSubjectByNameRequest1(MinjustService_getSubjectByName.XRoadClientIdentifierType client, MinjustService_getSubjectByName.XRoadServiceIdentifierType service, string userId, string id, string protocolVersion, MinjustService_getSubjectByName.getSubjectByNameRequest getSubjectByNameRequest)
        {
            this.client = client;
            this.service = service;
            this.userId = userId;
            this.id = id;
            this.protocolVersion = protocolVersion;
            this.getSubjectByNameRequest = getSubjectByNameRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSubjectByNameResponse1
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public MinjustService_getSubjectByName.XRoadClientIdentifierType client;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public MinjustService_getSubjectByName.XRoadServiceIdentifierType service;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string userId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string id;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://x-road.eu/xsd/xroad.xsd")]
        public string protocolVersion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tunduk.gov.kg", Order=0)]
        public MinjustService_getSubjectByName.getSubjectByNameResponse getSubjectByNameResponse;
        
        public getSubjectByNameResponse1()
        {
        }
        
        public getSubjectByNameResponse1(MinjustService_getSubjectByName.XRoadClientIdentifierType client, MinjustService_getSubjectByName.XRoadServiceIdentifierType service, string userId, string id, string protocolVersion, MinjustService_getSubjectByName.getSubjectByNameResponse getSubjectByNameResponse)
        {
            this.client = client;
            this.service = service;
            this.userId = userId;
            this.id = id;
            this.protocolVersion = protocolVersion;
            this.getSubjectByNameResponse = getSubjectByNameResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SubjectByNamePortChannel : MinjustService_getSubjectByName.SubjectByNamePort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SubjectByNamePortClient : System.ServiceModel.ClientBase<MinjustService_getSubjectByName.SubjectByNamePort>, MinjustService_getSubjectByName.SubjectByNamePort
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SubjectByNamePortClient() : 
                base(SubjectByNamePortClient.GetDefaultBinding(), SubjectByNamePortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SubjectByNamePortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubjectByNamePortClient(EndpointConfiguration endpointConfiguration) : 
                base(SubjectByNamePortClient.GetBindingForEndpoint(endpointConfiguration), SubjectByNamePortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubjectByNamePortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SubjectByNamePortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubjectByNamePortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SubjectByNamePortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SubjectByNamePortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MinjustService_getSubjectByName.getSubjectByNameResponse1> MinjustService_getSubjectByName.SubjectByNamePort.getSubjectByNameAsync(MinjustService_getSubjectByName.getSubjectByNameRequest1 request)
        {
            return base.Channel.getSubjectByNameAsync(request);
        }

        public System.Threading.Tasks.Task<MinjustService_getSubjectByName.getSubjectByNameResponse1> getSubjectByNameAsync(MinjustService_getSubjectByName.getSubjectByNameRequest1 inValue)
        {
            return ((MinjustService_getSubjectByName.SubjectByNamePort)(this)).getSubjectByNameAsync(inValue);
        }

        public System.Threading.Tasks.Task<MinjustService_getSubjectByName.getSubjectByNameResponse1> getSubjectByNameAsync(MinjustService_getSubjectByName.XRoadClientIdentifierType client, MinjustService_getSubjectByName.XRoadServiceIdentifierType service, string userId, string id, string protocolVersion, MinjustService_getSubjectByName.getSubjectByNameRequest getSubjectByNameRequest)
        {
            MinjustService_getSubjectByName.getSubjectByNameRequest1 inValue = new MinjustService_getSubjectByName.getSubjectByNameRequest1();
            inValue.client = client;
            inValue.service = service;
            inValue.userId = userId;
            inValue.id = id;
            inValue.protocolVersion = protocolVersion;
            inValue.getSubjectByNameRequest = getSubjectByNameRequest;
            return ((MinjustService_getSubjectByName.SubjectByNamePort)(this)).getSubjectByNameAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SubjectByNamePortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SubjectByNamePortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://example.org/xroad-endpoint");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SubjectByNamePortClient.GetBindingForEndpoint(EndpointConfiguration.SubjectByNamePortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SubjectByNamePortClient.GetEndpointAddress(EndpointConfiguration.SubjectByNamePortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            SubjectByNamePortSoap11,
        }
    }
}
